# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x10\x65xample.protobuf\")\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x11\n\tthumbnail\x18\x02 \x01(\t\"\x8a\x01\n\x06Result\x12\r\n\x05phase\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12(\n\x05trace\x18\x03 \x01(\x0b\x32\x17.example.protobuf.TraceH\x00\x12\x30\n\tthumbnail\x18\x04 \x01(\x0b\x32\x1b.example.protobuf.ThumbnailH\x00\x42\x06\n\x04\x64\x61ta\"l\n\x05Trace\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x0e\n\x06\x63hains\x18\x03 \x03(\t\x12\x11\n\tthumnbail\x18\x04 \x01(\x08\x12$\n\x04info\x18\x05 \x01(\x0b\x32\x16.example.protobuf.Info\"*\n\x04Info\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"+\n\tThumbnail\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42\x1dZ\x1b\x65xample.com/driver/protobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\033example.com/driver/protobuf'
  _REQUEST._serialized_start=32
  _REQUEST._serialized_end=73
  _RESULT._serialized_start=76
  _RESULT._serialized_end=214
  _TRACE._serialized_start=216
  _TRACE._serialized_end=324
  _INFO._serialized_start=326
  _INFO._serialized_end=368
  _THUMBNAIL._serialized_start=370
  _THUMBNAIL._serialized_end=413
# @@protoc_insertion_point(module_scope)

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST